### ISSUE TITLE
PRACTICA CONEXION

### ISSUE THREAD

**Issue by AricelCastro** [SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-equipoolaxd#1]
[PRACTICA CONEXION.pdf](https://github.com/SistemasTecTlaxiaco/actividad-10-conexion-a-bases-de-datos-equipoolaxd/files/15493330/PRACTICA.CONEXION.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..Calificacion 19
